name: Python Tests with Allure

on:
  workflow_dispatch:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

env:
  SHOP_HTTP_CLIENT__URL: http://127.0.0.1:3000
  SHOP_HTTP_CLIENT__TIMEOUT: 100

  EXPECT_TIMEOUT: 15000
  HEADLESS: true
  APP_URL: http://127.0.0.1:3000
  SLOW_MO: 500
  VIDEOS_PATH: "./videos"


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest

      - name: Install Playwright Browsers
        run: playwright install

      - name: Start Juice Shop
        run: |
          docker pull bkimminich/juice-shop
          docker run -d -p 3000:3000 --name juice-shop bkimminich/juice-shop
          - name: Wait for Juice Shop
            run: |
              n=0
              until curl -s http://127.0.0.1:3000; do
                n=$((n+1))
                if [ $n -gt 30 ]; then
                  echo "Server did not start in time"
                  exit 1
                fi
                sleep 1
              done

      - name: Run selected tests
        run: |
          # Запуск тестов с тегом smoke
          pytest tests/tests_frontend/ -m smoke --alluredir=allure-results5 --maxfail=5 -v

      - name: Generate Allure Report
        run: |
          pip install allure-commandline
          allure generate allure-results5 --clean -o allure-report

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
